LIB=	openbsd-compat
INTERNALLIB=

SRCS=	freezero.c \
	getdtablecount.c \
	imsg.c \
	imsg-buffer.c \
	open.c \
	recallocarray.c \
	strtonum.c \
	bsd-closefrom.c \
	fmt_scaled.c \
	reallocarray.c

CFLAGS+= -I${.CURDIR}

incinstall:

.include <bsd.lib.mk>
